"""packages/shared/src/enums.ts 的 Python 镜像。

契约测试（tests/test_contract.py）会与 shared/schemas/enums.json 做集合比对，
任何一端增减值都会失败。不要在这里单独新增枚举值。
"""

from enum import StrEnum


class TaskSource(StrEnum):
    MANUAL = "MANUAL"
    GITHUB_ISSUE = "GITHUB_ISSUE"
    WORKFLOW_RUN = "WORKFLOW_RUN"


class TaskStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    PR_CREATED = "PR_CREATED"
    PR_FAILED = "PR_FAILED"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class RunStatus(StrEnum):
    PENDING = "PENDING"
    DISPATCHED = "DISPATCHED"
    RUNNING = "RUNNING"
    VERIFYING = "VERIFYING"
    INTERRUPTED = "INTERRUPTED"
    RECOVERING = "RECOVERING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AttemptStatus(StrEnum):
    CLAIMED = "CLAIMED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CRASHED = "CRASHED"
    TIMED_OUT = "TIMED_OUT"
    LEASE_EXPIRED = "LEASE_EXPIRED"


class AgentKind(StrEnum):
    SELF_LANGGRAPH = "SELF_LANGGRAPH"
    MINI_SWE = "MINI_SWE"


class TraceEventType(StrEnum):
    MODEL_CALL = "MODEL_CALL"
    TOOL_CALL = "TOOL_CALL"
    FILE_CHANGE = "FILE_CHANGE"
    COMMAND_EXEC = "COMMAND_EXEC"
    STATE_TRANSITION = "STATE_TRANSITION"
    CHECKPOINT_SAVED = "CHECKPOINT_SAVED"
    FAILURE_DETECTED = "FAILURE_DETECTED"
    RECOVERY_ACTION = "RECOVERY_ACTION"
    VERIFICATION_RESULT = "VERIFICATION_RESULT"
    APPROVAL_EVENT = "APPROVAL_EVENT"
    BUDGET_UPDATE = "BUDGET_UPDATE"


class FailureCode(StrEnum):
    MODEL_RATE_LIMIT = "MODEL_RATE_LIMIT"
    MODEL_API_ERROR = "MODEL_API_ERROR"
    MODEL_BAD_OUTPUT = "MODEL_BAD_OUTPUT"
    TOOL_EXEC_ERROR = "TOOL_EXEC_ERROR"
    PATCH_APPLY_FAILED = "PATCH_APPLY_FAILED"
    SANDBOX_START_FAILED = "SANDBOX_START_FAILED"
    SANDBOX_CRASHED = "SANDBOX_CRASHED"
    WORKER_LOST = "WORKER_LOST"
    BUDGET_TOKENS_EXCEEDED = "BUDGET_TOKENS_EXCEEDED"
    BUDGET_TIME_EXCEEDED = "BUDGET_TIME_EXCEEDED"
    BUDGET_TURNS_EXCEEDED = "BUDGET_TURNS_EXCEEDED"
    AGENT_STUCK = "AGENT_STUCK"
    VERIFY_PATCH_MALFORMED = "VERIFY_PATCH_MALFORMED"
    VERIFY_SCOPE_VIOLATION = "VERIFY_SCOPE_VIOLATION"
    VERIFY_STATIC_FAILED = "VERIFY_STATIC_FAILED"
    VERIFY_TARGET_TESTS_FAILED = "VERIFY_TARGET_TESTS_FAILED"
    VERIFY_REGRESSION_FAILED = "VERIFY_REGRESSION_FAILED"
    VERIFY_TEST_TAMPERING = "VERIFY_TEST_TAMPERING"
    HUMAN_REJECTED = "HUMAN_REJECTED"
    CANCELLED_BY_USER = "CANCELLED_BY_USER"


class PolicyAction(StrEnum):
    RESUME = "RESUME"
    RESTART_ATTEMPT = "RESTART_ATTEMPT"
    ESCALATE_HUMAN = "ESCALATE_HUMAN"
    ABORT = "ABORT"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"


class ArtifactKind(StrEnum):
    PATCH = "PATCH"
    TEST_REPORT = "TEST_REPORT"
    LOG = "LOG"
    JUDGE_REPORT = "JUDGE_REPORT"


class RunCommandType(StrEnum):
    START_RUN = "START_RUN"
    RESUME_RUN = "RESUME_RUN"
    CANCEL_RUN = "CANCEL_RUN"


class VerifierStep(StrEnum):
    V1 = "V1"
    V2 = "V2"
    V3 = "V3"
    V4 = "V4"
    V5 = "V5"
    V6 = "V6"
